const CASE_CAREER = [
{
  id:"c_career_o1",type:"choice",title:"是否该换工作？",category:"事业",spread:"三牌阵",
  question:"案主问是否该换工作。",
  background:"工作三年，感到瓶颈，但担心换工作风险。",
  cards:[{pos:"过去",id:17,ori:"正位"},{pos:"现在",id:58,ori:"逆位"},{pos:"未来",id:0,ori:"正位"}],
  options:[
    {k:"A",t:"建议立刻裸辞"},
    {k:"B",t:"可以先准备，不必立刻裸辞"},
    {k:"C",t:"维持现状，不要动"},
    {k:"D",t:"问题在人际关系，换工作没用"}
  ],
  answer:"B",
  explanation:"过去星星正位说明原本有热情和希望；现在宝剑三逆位说明正在疗愈，伤痛在缓解；未来愚人正位鼓励重新出发。综合来看，适合先积累作品和人脉，再平稳过渡。",
  conclusion:"可以开始准备换工作，但不必立刻裸辞。",
  feedback:"三个月后案主换到新行业，状态明显改善。",
  tags:["换工作","事业","三牌阵"]
}
];