const CASES = [
{
  id:"c_love_01",type:"choice",title:"这段感情会怎么发展？",category:"爱情",spread:"单牌",
  question:"案主问这段感情未来三个月的发展。",
  background:"交往半年，最近沟通变少。",
  cards:[{pos:"现状",id:13,ori:"逆位"}],
  options:[
    {k:"A",t:"关系即将彻底结束"},
    {k:"B",t:"关系停滞，需要主动沟通"},
    {k:"C",t:"马上会结婚"},
    {k:"D",t:"对方已经变心"}
  ],
  answer:"B",
  explanation:"死神逆位表示关系停滞，不愿改变，但也没有彻底结束。需要主动沟通，否则会陷入僵局。",
  conclusion:"关系进入停滞期，主动沟通是关键。",
  feedback:"案主主动沟通后，关系有所缓和。",
  tags:["感情","单牌","停滞"]
},
{
  id:"c_love_02",type:"reveal",title:"我该不该继续这段关系？",category:"爱情",spread:"单牌",
  question:"案主问是否该继续这段关系。",
  background:"在一起两年，反复争吵，但舍不得分开。",
  cards:[{pos:"现状",id:15,ori:"正位"}],
  prompt:"先自己想一想，再点开解析。",
  explanation:"恶魔正位代表束缚与执念。这段关系可能有依赖、控制或不健康的模式，让案主难以离开。但恶魔的锁链其实很松，意味着束缚更多来自内心，而非外在。",
  conclusion:"需要看清关系中的执念与依赖，是否继续取决于能否打破不健康的模式。",
  feedback:"案主意识到自己的依赖模式，开始寻求独立。",
  tags:["感情","单牌","执念"]
}
];
